import { geminiJson } from "./gemini";
import type { Locale } from "./i18n";
import { getLibraryStats } from "./library";

/** A music persona — the listener anthropomorphized as a shareable character. */
export interface Persona {
  name: string; // catchy Korean nickname
  archetype: string; // short type label
  emoji: string; // one representative emoji
  tagline: string; // one punchy line
}

/** Music psychology / taste profile generated by Gemini. */
export interface AiProfile {
  persona: Persona;
  headline: string;
  personality: string;
  traits: string[];
  favoriteGenres: string[];
  avoidedGenres: string[];
  unexploredGenres: string[];
  moodProfile: string;
  diggingScore: number;
  diggingComment: string;
  improvementTips: string[];
}

const SCHEMA = {
  type: "OBJECT",
  properties: {
    persona: {
      type: "OBJECT",
      properties: {
        name: { type: "STRING" },
        archetype: { type: "STRING" },
        emoji: { type: "STRING" },
        tagline: { type: "STRING" },
      },
      required: ["name", "archetype", "emoji", "tagline"],
    },
    headline: { type: "STRING" },
    personality: { type: "STRING" },
    traits: { type: "ARRAY", items: { type: "STRING" } },
    favoriteGenres: { type: "ARRAY", items: { type: "STRING" } },
    avoidedGenres: { type: "ARRAY", items: { type: "STRING" } },
    unexploredGenres: { type: "ARRAY", items: { type: "STRING" } },
    moodProfile: { type: "STRING" },
    diggingScore: { type: "INTEGER" },
    diggingComment: { type: "STRING" },
    improvementTips: { type: "ARRAY", items: { type: "STRING" } },
  },
  required: [
    "persona", "headline", "personality", "traits", "favoriteGenres",
    "avoidedGenres", "unexploredGenres", "moodProfile", "diggingScore",
    "diggingComment", "improvementTips",
  ],
};

/** Library stats → Gemini psychological analysis. Saving to taste_profiles is the caller's job. */
export async function generateProfile(
  userId: string,
  locale: Locale,
  bypassCap = false,
): Promise<AiProfile> {
  const s = await getLibraryStats(userId);
  const diversity = s.total > 0 ? s.distinctArtists / s.total : 0;
  const lang = locale === "ko" ? "한국어" : "영어(English)";

  const prompt = `당신은 통찰력 있는 음악 취향 분석가입니다. 한 리스너의 유튜브 뮤직 "좋아요" 라이브러리 통계를 보고 심리·취향 프로파일과 '취향 보강 가이드'를 작성하세요.

[데이터]
- 총 좋아요 곡: ${s.total}
- 서로 다른 아티스트: ${s.distinctArtists} (다양성 비율 ${(diversity * 100).toFixed(0)}%)
- 분석 완료(장르/무드 보유): ${s.enriched}곡
- 자주 좋아한 아티스트: ${s.topArtists.map((a) => `${a.name}(${a.count})`).join(", ") || "데이터 없음"}
- 장르 분포: ${s.topGenres.map((g) => `${g.name}(${g.count})`).join(", ") || "데이터 없음"}
- 무드 분포: ${s.topMoods.map((m) => `${m.name}(${m.count})`).join(", ") || "데이터 없음"}
- 오디오 특성(0~1 평균): ${
    s.audioFeel
      ? `에너지 ${s.audioFeel.energy.toFixed(2)}, 템포 ${s.audioFeel.tempo.toFixed(2)}, 어쿠스틱 ${s.audioFeel.acousticness.toFixed(2)}`
      : "데이터 없음"
  }
- 자주 등장하는 악기: ${s.topInstruments.map((i) => i.name).join(", ") || "데이터 없음"}
- 앨범 몰입도: 3곡 이상 좋아한 앨범 ${s.albumDepth.deepAlbums}개, 좋아요 곡의 ${(s.albumDepth.concentration * 100).toFixed(0)}%가 그런 앨범에서 나옴
- 깊게 판 앨범: ${s.topAlbums.slice(0, 6).map((a) => `${a.name}(${a.count}곡)`).join(", ") || "데이터 없음"}

[작성 지시]
- ★ 모든 출력 텍스트(persona·headline·personality·traits·각 장르명·tips 등)는 반드시 ${lang}(으)로 작성. 친근하면서도 날카롭게.
- persona: 이 리스너를 '음악 캐릭터'로 의인화. 재미있고 공유하고 싶게.
  ★ 실제 아티스트·밴드·곡 이름은 절대 쓰지 말 것. 대신 장르·악기·분위기 기반의 '유형 틀'에서 골라 조합한다.
  유형 예시(데이터의 장르 분포에 맞는 것을 고를 것):
  락커 / 랩퍼 / 인디 음유시인 / EDM 레이버 / 피아노 낭만가 / 시티팝 드리머 / 재즈 보헤미안 /
  발라드 센티멘털리스트 / 메탈헤드 / 포크 방랑자 / 디스코 펑크 / R&B 크루너 / 슈게이저 /
  앰비언트 명상가 / 펑크 반항아 / 신스팝 몽상가 / 로파이 산책자.
  · name: '[수식어] [유형]' 형태의 멋진 ${lang} 별칭 (한국어 예: "심야의 시티팝 드리머" / 영어 예: "Midnight City-Pop Dreamer").
  · archetype: 위 유형 중 핵심 하나.
  · emoji: 캐릭터에 어울리는 이모지 1개.
  · tagline: 임팩트 있는 한 줄.
- headline: 이 사람의 음악 취향을 한 줄로 압축.
- 모든 항목에서 실제 아티스트·곡 이름 대신 장르·무드·악기·특성 언어로 서술할 것.
- personality: 음악 취향에서 드러나는 성격·정서를 2~3문장으로.
- traits: 취향 특징 키워드 3~6개.
- favoriteGenres: 데이터상 뚜렷한 선호 장르.
- avoidedGenres: 의식적으로 피하는 듯한 주요 장르(데이터에 거의 없음).
- unexploredGenres: 이 취향이면 좋아할 만한데 아직 안 들어본 장르 3~5개.
- moodProfile: 무드 분포와 오디오 특성(에너지·템포·어쿠스틱)을 엮어 정서적 경향을 1~2문장으로.
- diggingScore: 0~100 정수. 아티스트 다양성·장르 폭·마이너 장르 비중에 더해 **앨범 몰입도**(한 앨범을 깊게 파는지)도 함께 반영해 '음악 디깅 수준'을 평가. 싱글 위주로 흩어 듣기보다 앨범을 통째로 깊게 파는 사람을 디깅 수준이 높다고 본다.
- diggingComment: diggingScore 의 근거(다양성·앨범 몰입도 포함) + 점수를 올리려면 무엇이 필요한지 한 문장으로.
- improvementTips: 이 리스너의 취향에서 '보강하면 좋을 점' 4~6개. 각 항목은 한 문장으로 끝내지 말고 ① 무엇이 부족하거나 편향됐는지 ② 왜 그것을 보강하면 좋은지 ③ 구체적으로 어떤 하위장르·아티스트·곡부터 시작하면 좋은지 를 모두 담아 2~3문장으로 충실히 설명하세요. 막연한 조언이 아니라 실제 데이터(편중된 장르/무드, 낮은 다양성 등)에 근거해서.`;

  return geminiJson<AiProfile>(prompt, SCHEMA, { bypassCap });
}
