import { z } from "zod";
import { aiJson, sanitizeAiString } from "./ai";
import type { Locale } from "./i18n";
import { getLibraryStats } from "./library";

/** A length-bounded string that's scrubbed of URLs, bidi controls, and
 *  stray markdown fences before persistence. Used by every text field
 *  in the AI profile so any future model misbehaviour can't leak a
 *  clickable link into prose the user reads as authoritative. */
const safeStr = (min: number, max: number) =>
  z
    .string()
    .min(min)
    .max(max)
    .transform(sanitizeAiString)
    // re-assert min length AFTER sanitization — a string that was nothing
    // but URLs could pass the initial min check then collapse to empty.
    .refine((s) => s.length >= min, { message: `length below ${min} after sanitize` });

/** A music persona — the listener anthropomorphized as a shareable character. */
export interface Persona {
  name: string; // catchy Korean nickname
  archetype: string; // short type label
  emoji: string; // one representative emoji
  tagline: string; // one punchy line
}

/** Music psychology / taste profile generated by Gemini. */
export interface AiProfile {
  persona: Persona;
  headline: string;
  personality: string;
  traits: string[];
  favoriteGenres: string[];
  avoidedGenres: string[];
  unexploredGenres: string[];
  moodProfile: string;
  /** Overall digging score (0-100). Computed as the mean of axisScores
   *  if those are present; falls back to a Gemini-supplied single value
   *  for backward compat with profiles generated before the four-axis
   *  refactor (May 2026). */
  diggingScore: number;
  diggingComment: string;
  improvementTips: string[];
  /** Four-axis breakdown of the digging score. Optional because old
   *  profiles in taste_profiles don't have it; new generations always
   *  populate it and the UI shows the four bars + a derived overall
   *  number when present.
   *
   *  - genreBreadth: how wide the genre vocabulary is (entropy-style).
   *  - albumDepth:   how much listening sits in deeply-played albums
   *                  vs. one-off singles.
   *  - indieDepth:   how far from mainstream the artists trend
   *                  (Deezer rank distance / niche-genre share).
   *  - eraBreadth:   how spread-out across decades the library is. */
  axisScores?: AxisScores;
}

export interface AxisScores {
  genreBreadth: number;
  albumDepth: number;
  indieDepth: number;
  eraBreadth: number;
}

/** Runtime validation of Gemini's JSON. The TS interface above is a *type*
 *  hint at compile time; this schema is what actually rejects malformed
 *  responses before they corrupt the DB. Coerce + clamp where reasonable
 *  so minor model misbehaviour (e.g. diggingScore returned as a string)
 *  doesn't fail the whole generation. */
const PersonaZ = z.object({
  name: safeStr(1, 120),
  archetype: safeStr(1, 80),
  // emoji isn't run through sanitize: stripping bidi controls is fine but
  // the URL-scheme regex would eat legitimate "data:" -free emoji strings,
  // and the 8-char cap keeps abuse trivial.
  emoji: z.string().min(1).max(8),
  tagline: safeStr(1, 200),
});
const AxisScoresZ = z.object({
  genreBreadth: z.coerce.number().int().min(0).max(100),
  albumDepth: z.coerce.number().int().min(0).max(100),
  indieDepth: z.coerce.number().int().min(0).max(100),
  eraBreadth: z.coerce.number().int().min(0).max(100),
});
const AiProfileZ = z.object({
  persona: PersonaZ,
  headline: safeStr(1, 200),
  personality: safeStr(1, 2000),
  traits: z.array(safeStr(1, 60)).min(1).max(10),
  favoriteGenres: z.array(safeStr(1, 60)).max(10),
  avoidedGenres: z.array(safeStr(1, 60)).max(10),
  unexploredGenres: z.array(safeStr(1, 60)).max(10),
  moodProfile: safeStr(1, 2000),
  diggingScore: z.coerce.number().int().min(0).max(100),
  diggingComment: safeStr(1, 800),
  improvementTips: z.array(safeStr(1, 800)).max(8),
  // Optional so a model that ignores the new prompt section still
  // parses. Caller computes diggingScore from the four-axis mean
  // when present (overrides whatever Gemini wrote for it).
  axisScores: AxisScoresZ.optional(),
});

const SCHEMA = {
  type: "OBJECT",
  properties: {
    persona: {
      type: "OBJECT",
      properties: {
        name: { type: "STRING" },
        archetype: { type: "STRING" },
        emoji: { type: "STRING" },
        tagline: { type: "STRING" },
      },
      required: ["name", "archetype", "emoji", "tagline"],
    },
    headline: { type: "STRING" },
    personality: { type: "STRING" },
    traits: { type: "ARRAY", items: { type: "STRING" } },
    favoriteGenres: { type: "ARRAY", items: { type: "STRING" } },
    avoidedGenres: { type: "ARRAY", items: { type: "STRING" } },
    unexploredGenres: { type: "ARRAY", items: { type: "STRING" } },
    moodProfile: { type: "STRING" },
    diggingScore: { type: "INTEGER" },
    diggingComment: { type: "STRING" },
    improvementTips: { type: "ARRAY", items: { type: "STRING" } },
    axisScores: {
      type: "OBJECT",
      properties: {
        genreBreadth: { type: "INTEGER" },
        albumDepth:   { type: "INTEGER" },
        indieDepth:   { type: "INTEGER" },
        eraBreadth:   { type: "INTEGER" },
      },
      required: ["genreBreadth", "albumDepth", "indieDepth", "eraBreadth"],
    },
  },
  required: [
    "persona", "headline", "personality", "traits", "favoriteGenres",
    "avoidedGenres", "unexploredGenres", "moodProfile", "diggingScore",
    "diggingComment", "improvementTips", "axisScores",
  ],
};

/** Library stats → Gemini psychological analysis. Saving to taste_profiles is the caller's job. */
export async function generateProfile(
  userId: string,
  locale: Locale,
  bypassCap = false,
): Promise<AiProfile> {
  const s = await getLibraryStats(userId);
  const diversity = s.total > 0 ? s.distinctArtists / s.total : 0;
  const lang = locale === "ko" ? "한국어" : "영어(English)";

  const prompt = `당신은 통찰력 있는 음악 취향 분석가입니다. 한 리스너의 유튜브 뮤직 "좋아요" 라이브러리 통계를 보고 심리·취향 프로파일과 '취향 보강 가이드'를 작성하세요.

[데이터]
- 총 좋아요 곡: ${s.total}
- 서로 다른 아티스트: ${s.distinctArtists} (다양성 비율 ${(diversity * 100).toFixed(0)}%)
- 분석 완료(장르/무드 보유): ${s.enriched}곡
- 자주 좋아한 아티스트(전 기간): ${s.topArtists.map((a) => `${a.name}(${a.count})`).join(", ") || "데이터 없음"}
- 최근 자주 듣는 아티스트(최근 좋아요 위주): ${s.recentArtists.map((a) => `${a.name}(${a.count})`).join(", ") || "데이터 없음"}
- 장르 분포: ${s.topGenres.map((g) => `${g.name}(${g.count})`).join(", ") || "데이터 없음"}
- 무드 분포: ${s.topMoods.map((m) => `${m.name}(${m.count})`).join(", ") || "데이터 없음"}
- 오디오 특성(0~1 평균): ${
    s.audioFeel
      ? `에너지 ${s.audioFeel.energy.toFixed(2)}, 템포 ${s.audioFeel.tempo.toFixed(2)}, 어쿠스틱 ${s.audioFeel.acousticness.toFixed(2)}`
      : "데이터 없음"
  }
- 자주 등장하는 악기: ${s.topInstruments.map((i) => i.name).join(", ") || "데이터 없음"}
- 앨범 몰입도: 3곡 이상 좋아한 앨범 ${s.albumDepth.deepAlbums}개, 좋아요 곡의 ${(s.albumDepth.concentration * 100).toFixed(0)}%가 그런 앨범에서 나옴
- 깊게 판 앨범: ${s.topAlbums.slice(0, 6).map((a) => `${a.name}(${a.count}곡)`).join(", ") || "데이터 없음"}

[작성 지시]
- ★ 모든 출력 텍스트(persona·headline·personality·traits·각 장르명·tips 등)는 반드시 ${lang}(으)로 작성. 친근하면서도 날카롭게.
- ★ 다음은 절대 추론·기재하지 말 것: 사용자의 종교적 신념, 정치적 견해, 인종·민족·국적, 성적 지향, 정신 건강 상태(우울/불안 등), 의료 정보. GDPR 특수 카테고리 (Article 9) 침해 위험. 음악 자체의 일반적 분위기 묘사("우울한 발라드를 좋아함") 는 OK 이지만, 그 사람의 정신 상태("당신은 우울한 사람") 추론은 금지.
- persona: 이 리스너를 '음악 캐릭터'로 의인화. 재미있고 공유하고 싶게.
  ★ 실제 아티스트·밴드·곡 이름은 절대 쓰지 말 것. 대신 장르·악기·분위기 기반의 '유형 틀'에서 골라 조합한다.
  유형 예시(데이터의 장르 분포에 맞는 것을 고를 것):
  락커 / 랩퍼 / 인디 음유시인 / EDM 레이버 / 피아노 낭만가 / 시티팝 드리머 / 재즈 보헤미안 /
  발라드 센티멘털리스트 / 메탈헤드 / 포크 방랑자 / 디스코 펑크 / R&B 크루너 / 슈게이저 /
  앰비언트 명상가 / 펑크 반항아 / 신스팝 몽상가 / 로파이 산책자.
  · name: '[수식어] [유형]' 형태의 멋진 ${lang} 별칭 (한국어 예: "심야의 시티팝 드리머" / 영어 예: "Midnight City-Pop Dreamer").
  · archetype: 위 유형 중 핵심 하나.
  · emoji: 캐릭터에 어울리는 이모지 1개.
  · tagline: 임팩트 있는 한 줄.
- headline: 이 사람의 음악 취향을 한 줄로 압축.
- 모든 항목에서 실제 아티스트·곡 이름 대신 장르·무드·악기·특성 언어로 서술할 것.
- personality: 음악 취향에서 드러나는 성격·정서를 2~3문장으로.
- traits: 취향 특징 키워드 3~6개.
- favoriteGenres: 데이터상 뚜렷한 선호 장르.
- avoidedGenres: 의식적으로 피하는 듯한 주요 장르(데이터에 거의 없음).
- unexploredGenres: 이 취향이면 좋아할 만한데 아직 안 들어본 장르 3~5개.
- moodProfile: 무드 분포와 오디오 특성(에너지·템포·어쿠스틱)을 엮어 정서적 경향을 1~2문장으로.
- personality / moodProfile / improvementTips 작성 시, "전 기간 취향"과 "최근 자주 듣는 아티스트"가 명확히 다르면 그 변화를 짚어 주세요 — 예: "예전에는 X 위주였는데 요즘은 Y 쪽으로 옮겨가는 중". 둘이 비슷하면 굳이 언급하지 않아도 됩니다.
- axisScores: 네 부문 점수 (0-100 정수). 부문별로 독립 평가하고, "모든 축이 높아야 좋은 청자"가 아님을 유의. 부문이 한쪽으로 치우친 청자도 좋은 디깅일 수 있다.
  · genreBreadth: 장르 다양성. 장르 분포가 얼마나 넓은지 (한 장르 70%↑이면 낮음, 여러 장르 고르게 분포면 높음).
  · albumDepth: 앨범 몰입도. 한 앨범에서 여러 곡을 좋아하는지(통째로 듣는지) vs. 싱글 위주 흩어 듣기인지. 데이터의 "앨범 몰입도" 수치를 그대로 반영.
  · indieDepth: 인디 발굴 깊이. 메인스트림 / 유명 아티스트만 듣는지, 덜 알려진 마이너 장르·아티스트 비중이 큰지. 데이터의 장르 분포에서 마이너 / 비주류 비중을 추정.
  · eraBreadth: 시대 폭. 특정 시대(예: 2020s만)에 갇혀 있는지, 여러 시대(70s~현재)를 가로지르는지. 데이터에 정확한 정보 없으면 60 정도 중립값.
- diggingScore: axisScores 의 평균 (0~100 정수). 호환을 위해 단일 점수도 제공하지만 axisScores 가 본질.
- diggingComment: 어떤 축이 강하고 어떤 축이 약한지 + 부족한 축을 어떻게 보강할 수 있는지 1-2문장. "장르 폭은 좁지만 앨범을 깊게 파는 스타일" 같은 식.
- improvementTips: 이 리스너의 취향에서 '보강하면 좋을 점' 4~6개. 각 항목은 한 문장으로 끝내지 말고 ① 무엇이 부족하거나 편향됐는지 ② 왜 그것을 보강하면 좋은지 ③ 구체적으로 어떤 하위장르·아티스트·곡부터 시작하면 좋은지 를 모두 담아 2~3문장으로 충실히 설명하세요. 막연한 조언이 아니라 실제 데이터(편중된 장르/무드, 낮은 다양성 등)에 근거해서.`;

  // High-value, low-frequency call → bump to the better reasoning model.
  // Override via GEMINI_MODEL_PROFILE if it gets too expensive (defaults
  // to gemini-2.5-pro ≈ $0.014/call vs $0.0007 on 2.0-flash).
  const model = process.env.GEMINI_MODEL_PROFILE ?? "gemini-2.5-pro";
  const raw = await aiJson<unknown>(prompt, SCHEMA, { bypassCap, model, userId });
  const parsed = AiProfileZ.safeParse(raw);
  if (!parsed.success) {
    throw new Error(
      `AI profile schema mismatch: ${parsed.error.issues
        .slice(0, 3)
        .map((i) => `${i.path.join(".")} ${i.message}`)
        .join("; ")}`,
    );
  }
  const profile = parsed.data;
  // Override Gemini's single diggingScore with the actual mean of the
  // four axes when present — the overall number then provably reflects
  // the per-axis values shown right next to it (no "axes say 70/60/30/40
  // but the headline says 78" mismatch).
  if (profile.axisScores) {
    const { genreBreadth, albumDepth, indieDepth, eraBreadth } = profile.axisScores;
    profile.diggingScore = Math.round(
      (genreBreadth + albumDepth + indieDepth + eraBreadth) / 4,
    );
  }
  return profile;
}
